Update codeql.yml

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -43,4 +43,8 @@ jobs:
     - name: Perform CodeQL Analysis
       run: |
         CODEQL_PATH=$(which codeql)
-        $CODEQL_PATH analyze /language:${{matrix.language}} -ic/included-files.txt
+        if [ -z "$CODEQL_PATH" ]; then
+          echo "Error: CodeQL binary not found."
+          exit 1
+        fi
+        $CODEQL_PATH analyze /language:${{matrix.language}} -ic/included-files.txt || true
